### ISSUE TITLE
既にある資料との棲み分けを考える

### ISSUE THREAD

**Issue by daiki-akimoto-jdsc** [jdsc-eng/development-standard#12]
## Backgrouds
- 既に標準化を目指しているものとして [gcp-infra](https://github.com/jdsc-eng/gcp-infra) 、 Confluence の Knowledge がある
- これらとの統合、または棲み分けをどう実施していくか

## Tasks
- [x] 全員で 30 分話して課題と対策の認識合わせ
- [] 出した対策に対して対応を進める

## Outputs
- hoge

**Comment by shintaro123** [comment]
**決まったこと**
- development-srtandardリポジトリにソースをあげていく
- gcp-infraないで使えるものがある場合はPRを作成の上、gcp-infraから移行する
  - 大谷内さんに声かけて相談する！！！
